trigger:
- main
  
name: Deploy Orchestration solution to dev
  
stages:
- stage: Build
  displayName: Build and Publish
  jobs:
  - template: ./templates/build-template.yaml

- stage: Dev
  displayName: Deploy To Dev  
  jobs:
  - template: /pipelines/templates/deploy-template.yaml
    parameters: 
      environment: dev
      servicePrincipal: 'DO-SC-DEV'
      appName: 'logic-esbint-dev-orchestration-eastus2-01'
      poolName: 'DO-BA-DEV'