  
jobs:
  - job: BuildJob
    displayName: Copy and Publish Artifacts
    pool:
      vmImage: 'windows-latest'

    steps:
      - task: CopyFiles@2
        displayName: Copy files
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)'
          Contents: '**'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'

      - task: PublishBuildArtifacts@1
        displayName:  Publish build artifacts
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: '$(artifactName)'